### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] Inconsistency in the Hover effect in elements of the navbar 

### ISSUE THREAD

**Issue by bhimanshu1** [formbricks/formbricks#1158]
### Issue Summary

* There nav-bar of the home page contains an inconsistency in the color of the hover effect, between the first element(best practises) and the others
* The other bug is as you click the first element, which produces a drop-down menu but there is a border and a outline created out there which does not go away and makes the UI cluttered.

### Steps to Reproduce

1. Open Formbricks home page [Formbricks.com](https://formbricks.com/) 
2. Hover over the nav-bar (see the color inconsistency)
3. also click on the best practices element (border and outline bug)

### Expected behavior

* All the elements in the nav-bar should have the same color while hovered over them, which shows the consistency in the UI and also improves it.
* And when clicked on the first element that is (best practices), the outline and border should not be there, this would make it more spacious 

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/121747470/f2cc663e-44b0-4b87-9bb6-d003f3ccb85b)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
OS: [e.g. iOS]
Browser: [e.g. chrome, safari]
Version: [e.g. 22]
```

**Comment by bhimanshu1** [comment]
I would like to work on this issue, would be grateful if you assign it to me.

**Comment by 3xp10it3r** [comment]
Hey @bhimanshu1 I have started working on this...

**Comment by 3xp10it3r** [comment]
@jobenjada Can you please assign this to me, Raising the PR in 30 min.

**Comment by akshayw1** [comment]
@jobenjada Can I initiate a PR Please assign

**Comment by 3xp10it3r** [comment]
@akshayw1  @jobenjada Why this error, Im trying to raise the PR.

✔ Preparing lint-staged...
⚠ Running tasks for staged files...
  ❯ package.json — 1 file
    ❯ (apps|packages)/**/*.{js,ts,jsx,tsx} — 1 file
      ✖ prettier --write [FAILED]
      ◼ eslint --fix
    ↓ *.json — no files
    ↓ packages/database/schema.prisma — no files
↓ Skipped because of errors from tasks.
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ prettier --write:
[error] require() of ES Module /Users/digvijaygupta/Desktop/Learnings/open-source/formbricks/node_modules/prettier-plugin-tailwindcss/dist/index.mjs not supported.
[error] Instead change the require of /Users/digvijaygupta/Desktop/Learnings/open-source/formbricks/node_modules/prettier-plugin-tailwindcss/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.
husky - pre-commit hook exited with code 1 (error)

**Comment by 3xp10it3r** [comment]
@jobenjada Please Check PR #1176

**Comment by jobenjada** [comment]
@bhimanshu1 pls ship it today :)

**Comment by 3xp10it3r** [comment]
@jobenjada I have already raised the PR, Can you please assign this to me. 🥹🥹🥹 #1176

**Comment by 3xp10it3r** [comment]
> @jobenjada I have already raised the PR, Can you please assign this to me. 🥹🥹🥹 #1176
Please....

**Comment by bhimanshu1** [comment]
@jobenjada Thanks and will do it

**Comment by 3xp10it3r** [comment]
Hey @jobenjada I have taken care of Dark and Light mode and used best practices, also took care of text and icon color match , on open and on close state of show in PR #1176 
Please look at the Video before merging.

**Comment by bhimanshu1** [comment]
Hey @3xp10it3r it's not about taking care of dark and light mode, it's about how all the others elements look and how does our element mix up with other 😃,btw good luck
