### ISSUE TITLE
[FEATURE][FormTribe 🔥][50 Points]  Fixing Navbar to top while scrolling the Page

### ISSUE THREAD

**Issue by itzabhinavarya** [formbricks/formbricks#1170]
### Is your feature request related to a problem? Please describe.

While scrolling the landing page of the website, Navbar is not fixed after scrolling.
For more reference you can checkout the Feature no. #1054 .

Current Behaviour
<img width="960" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/cb20a06b-7209-4fac-ae16-72556bdd4233">
 

### Describe the solution you'd like

Expected Behaviour
In Light Mode:

<img width="959" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/10aebd61-4121-4458-892b-787957fdadbb">

In Dark Mode:
<img width="960" alt="image" src="https://github.com/formbricks/formbricks/assets/95561280/b471958e-7eb3-4524-9248-077871c6f435">

### Additional context

I had raised a PR regarding this solution, But my PR got closed by @ShubhamPalriwala because they want to give a change to create a PR by the person who had raised the feature, so @ShubhamPalriwala give me 24hrs if he/she created a PR then that will be consider but it is now already out of time so now i am creating a PR. I would like to request @jobenjada & @ShubhamPalriwala Sir to review my PR. 

will soon mention the PR no.

Please Consider.

**Comment by itzabhinavarya** [comment]
@ShubhamPalriwala @jobenjada Sir, Please check the PR no. #1172

**Comment by 3xp10it3r** [comment]
Hey @itzabhinavarya 

do you know why Im getting  below thing while commiting ?

✔ Preparing lint-staged...
⚠ Running tasks for staged files...
  ❯ package.json — 1 file
    ❯ (apps|packages)/**/*.{js,ts,jsx,tsx} — 1 file
      ✖ prettier --write [FAILED]
      ◼ eslint --fix
    ↓ *.json — no files
    ↓ packages/database/schema.prisma — no files
↓ Skipped because of errors from tasks.
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ prettier --write:
[error] require() of ES Module /Users/digvijaygupta/Desktop/Learnings/open-source/formbricks/node_modules/prettier-plugin-tailwindcss/dist/index.mjs not supported.
[error] Instead change the require of /Users/digvijaygupta/Desktop/Learnings/open-source/formbricks/node_modules/prettier-plugin-tailwindcss/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.
husky - pre-commit hook exited with code 1 (error)

**Comment by itzabhinavarya** [comment]
Hello @3xp10it3r 
I think you don't have installed or the lastest version of prettier.
Kindly install/update prettier, It might resolve your issue.

**Comment by 3xp10it3r** [comment]
I tried it but no luck
@itzabhinavarya

**Comment by itzabhinavarya** [comment]
@3xp10it3r Are you running it locally or by using gitpod?

**Comment by itzabhinavarya** [comment]
@3xp10it3r , Try these following:

1. npm install prettier@latest prettier-plugin-tailwindcss@latest --save-dev

2 . in package.json use
{
  "type": "module",
  // ...other package.json settings
}

**Comment by 3xp10it3r** [comment]
> @3xp10it3r Are you running it locally or by using gitpod?

Locally

**Comment by 3xp10it3r** [comment]
> @3xp10it3r , Try these following:
> 
> 1. npm install prettier@latest prettier-plugin-tailwindcss@latest --save-dev
> 
> 2 . in package.json use { "type": "module", // ...other package.json settings }

tried but not able to resolve

**Comment by itzabhinavarya** [comment]
@3xp10it3r Same error ? or something else.

**Comment by 3xp10it3r** [comment]
same error, tried on gitpod, there also the same error

**Comment by itzabhinavarya** [comment]
@3xp10it3r You should check error in this file
Instead change the require of /Users/digvijaygupta/Desktop/Learnings/open-source/formbricks/node_modules/prettier-plugin-tailwindcss/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.

**Comment by 3xp10it3r** [comment]
hey @itzabhinavarya Can you share me the same files 5 lines from the top (index.mjs in dist)

**Comment by itzabhinavarya** [comment]
You can get that file from github.com/formbricks/formbricks
or you can also checkout and reverte back the changes or pull the raw file
from the origin.
You should google it how can you achieve this.
If you want those lines only then navigate to the Formbricks repo and
follow the hierarchy structure to reach out to that particular file.
You can get the file path from your code editor on the just below of the
file name. But this is not a good way because that changes also be shown in
the PR that you had made these changes.
So try to getting back the file from the origin by reverting back or
fetch/pull the raw file from the origin upstream.

**Comment by abhayv290** [comment]
Ok lets do this

**Comment by jobenjada** [comment]
@itzabhinavarya its yours, thanks for following up. We'll only merge this if its works smoothly, please test extensively 🙏

**Comment by itzabhinavarya** [comment]
@jobenjada Sir, I have tested the code at my end and everything is working fine and smoothly, I also navigated to the another section with the links and all are working perfecly. 
Must verify the code at your end also, and let me know if there any changes required.

BTW @jobenjada Sir, I need some guide by your side. Kindly check my latest comment in the PR no. #1172

**Comment by abhayv290** [comment]
Hey This is ABhay A mernstack developer ,
Assign me this issue I can fix this  I am curretly working on my personal project in React.js usign taliwind as styler so i know i can fix this

**Comment by itzabhinavarya** [comment]
Hello @abhayv290 ,Thanks for your intrest in this feature/issue, but as i have already fixed this and created a PR also. Do check and find more issues by your end. Make sure to read the contributing/contribuition guideline in this repo.
Thank you.

**Comment by Niranjan-Baur** [comment]
Hi @3xp10it3r , Are you able to solve this issue?

✔ Preparing lint-staged...
⚠ Running tasks for staged files...
  ❯ package.json — 2 files
    ❯ (apps|packages)/**/*.{js,ts,jsx,tsx} — 2 files
      ✖ prettier --write [FAILED]
      ◼ eslint --fix
    ↓ *.json — no files
    ↓ packages/database/schema.prisma — no files
↓ Skipped because of errors from tasks.
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ prettier --write:
[error] require() of ES Module /workspace/formbricks/node_modules/prettier-plugin-tailwindcss/dist/index.mjs not supported.
[error] Instead change the require of /workspace/formbricks/node_modules/prettier-plugin-tailwindcss/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.
husky - pre-commit hook exited with code 1 (error)
