### ISSUE TITLE
[Improvement] Formbricks-com: Add a copy button/icon on Setup Tabs

### ISSUE THREAD

**Issue by Bitnagar** [formbricks/formbricks#1181]
### Is your feature request related to a problem? Please describe.

We should add a `copy` button in the Setup tabs. Currently the users have to manually copy the code.

We should also fix the `HTML` code because it is not readable.

![setupTabs-FB](https://github.com/formbricks/formbricks/assets/88842947/e601442f-9112-4e3b-a801-bbd65208c693)

### Describe the solution you'd like

Add a `copy` button/icon besides the code so that users can copy it easily. Fix the `HTML` code readability. Both will definitely improve the user experience.

**Comment by Bitnagar** [comment]
Hey Team. If you consider this enhancement, Please assign it to me!

**Comment by krishpatel023** [comment]
Hey, I want to work on this one. Can you assign this to me?

**Comment by Bitnagar** [comment]
@codeZera11 Please do not work on issues that are not assigned to you. The design is pathetic 💩. This is not about sending a PR. We are about to Launch on Product Hunt. This is something serious.

**Comment by CodeZera11** [comment]
> @CodeZera11 Please do not work on issues that are not assigned to you.

From the place where I learned about open source, I was taught that instead of asking admins for assigning issues to you, you can directly start working on a issue if it hasn't already been assigned to someone. This is what open source is all about: collaboration and learning.

**Comment by Bitnagar** [comment]
@CodeZera11 That's just rude and very unprofessional. Kindly re-consider your learnings and respect others time and efforts. I have contributed earlier and you should get it assigned first. This is not about just raising a PR. You did it in such a hurry that the design looks horrible!

**Comment by CodeZera11** [comment]
> @CodeZera11 That's just rude and very unprofessional. Kindly re-consider your learnings and respect others time and efforts. I have contributed earlier and you should get it assigned first. This is not about just raising a PR. You did it in such a hurry that the design looks horrible!

I think instead of me answering admins should answer you and if you think that design is horrible then its an open source project and there are not limits of raising PR's, so just make a PR and submit it. If admins think your design is better they will merge your PR.

And i do respect others time and efforts.

Peace

**Comment by CodeZera11** [comment]
I just got to know that this repo has rules regarding assigning the issue first. Sorry man @Bitnagar just a rookie mistake

**Comment by CodeZera11** [comment]
Hey admins, can you assign this issue to me then i will reopen that PR

**Comment by jobenjada** [comment]
Hey! This isn't required, because no website visitor will copy this code snippet into their app, bc its not connected to THEIR Formbricks instance.

What someone can work on is making the code block look slicker like in our Docs.

Im closing this issue, but feel free to open a new one re the restyling in dark mode 🙏
