### ISSUE TITLE
[BUG] Webhook not sending all responses

### ISSUE THREAD

**Issue by litecactus** [formbricks/formbricks#1244]
### Issue Summary

I'm sending webhooks on the creation of a new response to a form. Webhook is received.
Docs say form responses should be listed in the data.data but only the first response can be seen.

I have pasted the response body below and made the form first question response visible in bold. There are 7 questions so only the first is showing. You can see in the response below that the answer to question 1 (id yz51gn52erhqn269lkz29l22) is _name_. I'd expect all of them to show?

I tried reading the webhook via two different methods (n8n and make) and both show the same behaviour. I guess its something I'm doing wrong?

{"webhookId":"clnt2xxxxxxe49txib","event":"responseCreated","data":{"id":"clntxxx9ju","createdAt":"2023-10-16T20:33:22.474Z","updatedAt":"2023-10-16T20:33:22.474Z","surveyId":"clnt2l9tlxxxxx44","person":null,"personAttributes":null,"finished":false,"data":{**"yz51gn52erhqn269lkz29l22":"name"**},"notes":[],"tags":[],"meta":{"url":"","userAgent":{"browser":"Chrome","os":"Mac OS"}},"singleUseId":null}}

### Steps to Reproduce

1. Create a form with multiple questions
2. Add a webhook to trigger on the form completion via integrations menu > webhook
3. read received data

### Expected behavior

I'd expect each of the forms questions responses to be listed in the webhook body data.data field 

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:MacOS
- Node:
- npm:
```

**Comment by ShubhamPalriwala** [comment]
Hey @litecactus, the reason you are facing the above scenario is:

- A response is created when a user submits the first question of the survey (hence the webhook gets triggered and you only get 1 answer)

To get for all the responses in a survey instance, you can take use of our other trigger `Response Finished` so that you get all the answers to that survey and gets triggered when the response is finished!


Let me know if the above helps your case or if you're looking for something else

**Comment by litecactus** [comment]
Oh well that's embarrassing! Thank you very much
