### ISSUE TITLE
[FEATURE] Add Better CSS Buttons to Cards in Integrations Tab

### ISSUE THREAD

**Issue by varundhand** [formbricks/formbricks#1276]
### Is your feature request related to a problem? Please describe.

The current styling of the buttons at the Integrations tab looks bland and does not blend in with the overall website theme and color. The addition of better CSS buttons will improve the user experience and make the website look more cohesive.

### Describe the solution you'd like

I have created better CSS buttons that blend in with the overall website theme and color.

<img width="421" alt="Screenshot 2023-10-18 at 1 14 08 AM" src="https://github.com/formbricks/formbricks/assets/110025628/83448068-5873-4bf3-a840-2839c2fc3b59">

### Additional context

_Before:_

<img width="734" alt="Screenshot 2023-10-18 at 1 01 50 AM" src="https://github.com/formbricks/formbricks/assets/110025628/98c664ea-ebc8-4fb9-8162-21d827e3375b">

_After:_

<img width="1462" alt="Screenshot 2023-10-18 at 1 02 06 AM" src="https://github.com/formbricks/formbricks/assets/110025628/4c4365aa-c1ec-4c08-ba76-d40591cf8043">

## Note to Reviewer:
 
I would like to work on this issue. Please assign it to me. Also, please label it as `hacktoberfest` and `hacktoberfest-accepted`.

**Comment by ShaikhZayan** [comment]
I Would Like To Solve This Issue #1276

**Comment by ShaikhZayan** [comment]
I Would Like To Take This

**Comment by ShubhamPalriwala** [comment]
Hey @varundhand, thanks for creating an issue! However we'd like to keep the colors of the Docs Button in the Integration Cards same as before because:
- It's not a primary button (ie the primary CTA for a user will be to check the webhook out) hence it has to have a lower visual pull than the Connect buttons
- Usually, gradients that have a text overlay are not great for accessibility as it reduces the visibility.

**Comment by jobenjada** [comment]
What @ShubhamPalriwala says, thanks for thinking along tho :)
