### ISSUE TITLE
[BUG][FormTribe 🔥][50 Points] progress bar on preview does not work properly on clicking welcome card

### ISSUE THREAD

**Issue by devuser200** [formbricks/formbricks#1303]
### Issue Summary

When repeatdly clicking on welcome card, the progress bar moves near the end in the preview section

### Steps to Reproduce

1. go to surveys
2. create new survey
3. click on welcome card multiple times

### Expected behavior

the progress bar should not be moving towards the end

### Other information

https://www.loom.com/share/2925c8cec03e43bc89c497f22ed37da3?sid=024d6856-d5fe-4807-ac8e-dbc5c19f9775

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Browser: Chrome
```

**Comment by devuser200** [comment]
Hey @jobenjada . I'm new to contributions, started during the hacktoberfest. I was initially working on #1289, and while working found the bug #1303 . Also I found another one where deleting the questions from top would make the preview section blank like #1289.
https://www.loom.com/share/bef3ec08a0f64f66a3e6c171f6fa8fc6?sid=403465b9-20fa-405b-abd3-91bed8010d13

I was working on gitpod which was new for me, and made these changes which took time, that solves these issues.
I later saw you had already assigned the issue #1289  so, I thought instead of creating new issue here.
I have created a PR #1304 .

**Comment by devuser200** [comment]
Hey @jobenjada I did not open another issue. I don't need points as I am wayy behind. 
I have solved the above issue, with the empty card on deletion issue and this issue  #1289  in a PR I raised here #1304 . You can review it, if it is correct.
This video shows all three issues corrected
https://www.loom.com/share/a12527c052964009adc32adc64bcf382?sid=4e632b07-57a9-487c-8ca5-a19c5519acb2

**Comment by devuser200** [comment]
Hey @jobenjada @Dhruwang , maybe change the design of the progress bar like this: https://www.loom.com/share/28caaaa39cff41de9037b9a40461dc0b?sid=afd6e70c-408a-4b8a-a1e7-300db7f3e65e

**Comment by raghavnagar7** [comment]
It seems like you're reporting an issue related to a specific software or web application, Formbricks, and how it behaves when repeatedly clicking on the "welcome card" in the "surveys" section. To address this issue, you may want to consider the following steps:

**1. Confirm the Issue:**
   - Ensure that the issue persists and is not due to a temporary glitch.

**2. Clear Browser Cache:**
   - Sometimes, caching issues can affect the behavior of web applications. Try clearing your browser cache and cookies, then attempt to reproduce the issue.

**3. Check for Browser Extensions:**
   - Certain browser extensions or add-ons might interfere with the functionality of web applications. Disable any extensions that may be causing conflicts and check if the issue still occurs.

**4. Browser Version:**
   - Make sure you're using an up-to-date version of Chrome, as using outdated browsers can lead to compatibility issues.

**5. Browser Compatibility:**
   - Verify that the web application is officially supported on the browser you're using (in this case, Chrome).

**6. Isolated Testing:**
   - Test the issue on different devices and browsers to see if the problem is specific to your setup.

**7. Contact Formbricks Support:**
   - If the issue persists and seems to be a problem with the Formbricks application, reach out to Formbricks support. Provide them with the information you've collected and the steps to reproduce the issue.

**8. Provide Additional Information:**
   - In your report, include the version of Formbricks you're using, the URL of the application, and any relevant details about the welcome card and survey setup. The provided video link might also be helpful for Formbricks support to diagnose the problem.

Remember to work closely with the Formbricks support team, as they will be the most knowledgeable and equipped to address issues specific to their application. They may be able to provide you with a solution, a workaround, or information on any known issues and fixes.
