### ISSUE TITLE
[BUG]:In Dark Mode Navbar is not Properly Visible

### ISSUE THREAD

**Issue by JiyaGupta-cs** [formbricks/formbricks#1463]
### Issue Summary

The navbar is not properly visible, it is getting merged with the background.

### Steps to Reproduce

1.  Went to [https://formbricks.com/concierge](https://formbricks.com/concierge)
2. Changed to Dark Mode
3. Scroll Down
4. You will see it like the screenshot

### Expected behavior

The navbar should be properly visible, it should not merge with the background.

### Screenshots

![image](https://github.com/formbricks/formbricks/assets/140608790/13cacfea-e23a-4c4d-8220-14723f8ce5dc)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

### Other information

**Please assign this issue to me.**

**Comment by Hamm01** [comment]
Hi can you please assign this issue to me . Thankyou

**Comment by crocmons** [comment]
Can I take this issue?

**Comment by HimanshuMahto** [comment]
Hey, @JiyaGupta-cs @chetan @kof @npaulsen  can i work on this issue please

**Comment by hemantmm** [comment]
Hi, @JiyaGupta-cs @chetan I would like to work on this issue.

**Comment by Sandy-1711** [comment]
Hey there @JiyaGupta-cs , I have fixed the bug and as this is the first ever contribution that I am making, so I do not know the guidelines of creating a pull request, should I just create a pull request, or someone will assign the issue to me. 
Before
![image](https://github.com/formbricks/formbricks/assets/121814590/efda92dd-fba6-42d3-9ea2-5af72f70aa9b)

After
![Screenshot 2023-10-26 140611](https://github.com/formbricks/formbricks/assets/121814590/ccb16e3e-b20e-4e85-bfa2-2af50868685b)

Please help me out.

**Comment by JiyaGupta-cs** [comment]
@mattinannt Please assign this issue to me since I figured this issue and opened it.

**Comment by jobenjada** [comment]
Hey @JiyaGupta-cs  - we are laser focused on the launch coming up next Tuesday.

Please focus all of your energy on finding bugs in our actual product - **not our landing page.**

I have now updated the side quests, so you will get 50 Points for flagging this issue just in case this wasn't clear to you :) 

@Sandy-1711 will also get 50 points because the solution was literally one line of code.

Anything more complex is just a distraction for our team at this moment.

Thanks for understanding 🙏
