### ISSUE TITLE
[BUG][100 Points] 'Paste url' field of Url shortner modal doesn't clear after closing the modal

### ISSUE THREAD

**Issue by rohan9896** [formbricks/formbricks#1501]
### Issue Summary

https://www.loom.com/share/084d5f80ef054e83b3ffa5bdd707af00?sid=1925df75-fde5-45fc-8cce-89d1e609f96f

When I paste some URL in the URL shortener modal, after closing and reopening it again, it resets the shortened URL but the long URL remains there in the form.

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

### Expected behavior

The long URL should also be reset along with the short URL.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by raghavnagar7** [comment]
**1. Contact Formbricks Support (Formbricks Cloud Users):**
   - If you are using Formbricks Cloud, reach out to Formbricks support through their official support channels. They will be able to investigate and assist you with the issue.

**2. Check Browser Compatibility:**
   - Make sure you're using a browser that is officially supported by Formbricks. Ensure that your browser is up-to-date.

**3. Clear Cache and Cookies:**
   - Clear your browser's cache and cookies, as outdated data in the browser cache can sometimes lead to issues.

**4. Disable Browser Extensions:**
   - Temporarily disable any browser extensions or add-ons that may be causing conflicts with Formbricks.

**5. Provide Additional Information:**
   - When contacting Formbricks support, provide them with details about the issue, including the steps to reproduce it and the URL you're using in the URL shortener. Any error messages or behaviors you've observed will also be helpful.

**6. Verify Self-hosted Setup (Self-hosted Users):**
   - If you're using a self-hosted Formbricks setup, ensure that you have the correct versions of Node.js and npm installed and that your server configuration is correct. The OS, Node, and npm versions can be important for troubleshooting any server-related issues.

**7. Consult Formbricks Documentation and Community:**
   - In the absence of a direct response from Formbricks support, consult any available documentation or community forums related to Formbricks. Other users may have encountered and solved similar issues.

To expedite the resolution of the problem, it's essential to reach out to Formbricks support, as they will have a better understanding of their platform and can provide guidance specific to your situation. Include all relevant information about the issue you're facing when you contact them.

Additionally, you may want to document the issue carefully and consider any workarounds until the issue is resolved to minimize its impact on your workflow.
