### ISSUE TITLE
[FEATURE][🕹️] Question Type: Signature 

### ISSUE THREAD

**Issue by dillfrescott** [formbricks/formbricks#1578]
### Describe the solution you're looking for

Add a signature question type to Formbricks that allows respondents to leave their signature.

**In the Survey Editor**
- Please add a new `SignatureQuestionForm` to the Survey Editor. Only `Question` and `Description` and the option to make the question optional should be provided as customization options.
- Add a new `SignatureQuestion` to the surveys package (`packages/surveys`). The surveys package runs with Preact. We can use the signature pad from [Documenso repository](https://github.com/documenso/documenso) so it requires a bit tinkering to get it ready for Preact. We should also only sideload this on demand. Please have a look at the `DateQuestion` to see how we do sideloading.
- For the question type, you can use our file upload infrastructure to store the signature image in Formbricks.

**On the Summary View**
- For the summary view, please show a bar graph of how many people signed.

**On the Response View**
- Please display the captured signature along with the date of the response

### Additional info

Have a look on [documenso.com](https://documenso.com) to see the signature pad:
<img width="576" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/ea467bcb-1ddc-4aa7-ad02-80017d540230">

**Comment by mattinannt** [comment]
@dillfrescott Thanks for bringing this up. We are currently laying the groundwork to sideload more complex question types into formbricks-js to avoid increasing the bundle size with all these new question types. This should be done in the next two weeks and then we can start working on the signature question type 😊.

**Comment by mattinannt** [comment]
Since the number of users requesting this feature is growing, let's be more specific:

### Describe the solution you're looking for

Add a signature question type to Formbricks that allows respondents to leave their signature.
- Please add a new `SignatureQuestionForm` to the Survey Editor. Only `Question` and `Description` and the option to make the question optional should be provided as customization options.
- Add a new `SignatureQuestion` to the surveys package (`packages/surveys`). Since we may need to use a react package to handle the signature, make sure it has a small bundle size. We should also only load this on demand. Please have a look at the `DateQuestion` to see how we did it.
- For the question type, you can use our file upload infrastructure to store the signature image in Formbricks.
- For the summary, please show a bar graph of how many people signed.

### Additional info

Here is how the component looks in tally.so
<img width="553" alt="Screenshot 2024-02-06 at 08 52 55" src="https://github.com/formbricks/formbricks/assets/675065/5c9461fe-0388-4f49-bebf-1f1239ec6f02">.

**Comment by jobenjada** [comment]
Had a chat with @ElTimuro and we can use the signature pad from the Documenso Repo 😍 

Please also add the "Powered by Cal.com" badge to the scheduling question:

<img width="942" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/c4b2fbf3-4111-42b1-b917-a14a9c2087a7">

**Comment by ElTimuro** [comment]
- Nice that you asked, it is open source after all :)
- Would be awesome to this you guys use this in the form of a reusable package more people can use, but do what works best for you
- We will eventually offer components as well, will take some time though

**Comment by jobenjada** [comment]
closing for now as it doesn't align so well with product focus

**Comment by mmcgahan** [comment]
I understand it's not part of the current product focus, but I'd like to request that this issue be re-opened, even if it doesn't appear on a development roadmap in the near future - offering a product that passes the lawyer test for e-signing contracts would be amazing, and it's been a feature request for a long time for [competing products](https://community.typeform.com/build-your-typeform-7/signature-box-4589), so seems like it would be a great way to differentiate.
