### ISSUE TITLE
[BUG] Too Many Requests 429

### ISSUE THREAD

**Issue by danilofuchs** [formbricks/formbricks#1717]
### Issue Summary

Many customers are receiving 429 Too Many Requests when interacting with the SDK.

Our workflow is very simple:
- Init with user id
- Set email
- Set attribute companyId
- Handle route change

This init happens on every page refresh. We are thinking about saving some flag to `window` to avoid running it many times.

### Steps to Reproduce

1. Implement the SDK
2. Navigate the app, reload the page some times

### Expected behavior

Allow more requests from users.

### Environment

- [x] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by mattinannt** [comment]
@danilofuchs thanks for creating the issue. Running the init call multiple times shouldn't be an issue, since we are also storing information in local storage so we don't resync on every init call (we only do a resync every 15 minutes). Also the attributes endpoint should also be triggered when there is a change to the attributes. Are you already using the latest version of `@formbricks/js` (1.2.6)?

Our rate limiting triggered after 50 requests per hour from the same IP address. I now increased it to 60 calls every 15 minutes.
Can you please make sure you have the latest version of `@formbricks/js` and check again :-)

**Comment by ShubhamPalriwala** [comment]
Hey @danilofuchs, how's it going now? Did you experience this again?

**Comment by danilofuchs** [comment]
This issue is solved now. Thanks!
