### ISSUE TITLE
[FEATURE] Question Type: Contact Details (email, name, phone, address, social links)

### ISSUE THREAD

**Issue by regevaz** [formbricks/formbricks#1738]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

Provide a question of type "contact details" so that someone fills a form can have a single page to put his details such as:
Email, First name, Last name, Phone, social profile link

### Describe alternatives you've considered

Currently it is possible to achieve this by having multiple questions which causes the user experience to be less optimal

**Comment by mattinannt** [comment]
Thanks for opening an issue. I think it's a good feature to improve usability while collecting all contact information. We need to do some testing on how this would work for in-app surveys as our space there is limited. Currently we only support one question per view. Since this is a fundamental change, it may be a while before we make a decision.

**Comment by dhruvgupta0503** [comment]
Hii, I would like to work on this issue...

**Comment by mattinannt** [comment]
@regevaz We just merged the Question Type Address ( https://github.com/formbricks/formbricks/pull/2162 ).
<img width="1965" alt="Screenshot 2024-04-11 at 16 11 10" src="https://github.com/formbricks/formbricks/assets/675065/bbac6c19-28c4-4ef2-9b68-85319ae419fc">

We will also check if we can transform this concept to basic contact information :-)

**Comment by pbmagnet4** [comment]
Hoping to see this revived. Seems like a basic functionality that would be very helpful.
