### ISSUE TITLE
[FEATURE] Close button visibility (especially for centered in-app surveys)

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2098]
### Is your feature request related to a problem? Please describe.

We just noticed that centered in-app surveys cannot be closed. I would suggest to add a toggle to enable or remove the X. This way you can choose if you want to show or hide the close button for all types of in-app surveys.

### Describe the solution you'd like

Add an option "Hide Close Button" to the survey styling settings. This way you can show a close button also for centered surveys.

**Comment by mattinannt** [comment]
@Dhruwang Can you please check if this issue is fixed with the latest version of Formbricks?
<img width="948" alt="Screenshot 2024-04-11 at 16 15 12" src="https://github.com/formbricks/formbricks/assets/675065/3fa8ea8b-5c5a-4224-821f-12160d36854e">

Since we have the allow-exit functionality, if exit is allowed, an `X` icon should also be shown.
