### ISSUE TITLE
Multi-Language questions

### ISSUE THREAD

**Issue by mipapo** [formbricks/formbricks#221]
### Is your proposal related to a problem?

We have an multi language app and would like to localize the questions and answers.

### Describe the solution you'd like

Add an option to add supported language and add a corresponding translation.
Auto-Detect the language based on browser language + optional add an language attribute

**Comment by mattinannt** [comment]
@mipapo what languages does your app support?
How do you decide which language to display? Would it be enough to pass the language to the `formbricks.init()` call or do you need a e.g. separate `formbricks.setLanguage()` method?

**Comment by mipapo** [comment]
@mattinannt  German, English, Polish, Italian, Dutch, French, Norwegian, Catalan
I think a setLanguage() method makes more sense.

**Comment by mattinannt** [comment]
Awesome. We will come up with a concept for supporting multi language functionality (for the widget / your users) and give our best to fit it into one of the next bigger releases.

**Comment by mattinannt** [comment]
Update: Our team is currently working on the multi-language functionality. 😊

**Comment by Ale1x** [comment]
Any update? 

Would love to help for the italian translation.

**Comment by mattinannt** [comment]
@Ale1x There are two different functions: 
1. Ability to create surveys that can be viewed by survey participants in different languages.
2. Having the admin interface in different languages

Currently, we are only working on the first one and postponing the second one until we reach a certain codebase & feature stability of Formbricks, since maintaining multiple languages in the admin interface has a huge impact on our iteration speed.

**Comment by geoHeil** [comment]
The admin interface can stay in English. But I would love to see customizable languages for what the user sees. I am interested in German.

**Comment by mattinannt** [comment]
Update: The feature is currently being under heavy development in https://github.com/formbricks/formbricks/pull/1630 and is 90% complete. Next week we will move into a testing and review phase and will likely be able to merge it soon 😊💪

**Comment by arghaffari** [comment]
impatiently waiting for it 😊

**Comment by mattinannt** [comment]
@arghaffari @mipapo @geoHeil Sorry for the late response. The multi language feature is live on Formbricks Cloud and will be included in the next 1.7 release (as an Enterprise feature).
More info about the feature in our twitter post last week: https://twitter.com/formbricks/status/1770422428235153737

The development took way longer than expected because the feature touches the core of Formbricks (survey management) and thus was hard to get all the edge cases right. Thank your for your patience 🤗
