### ISSUE TITLE
[BUG] regression: OpenTextSummary no longer has "Show more" button

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2336]
### Issue Summary

It seems like this PR removed the "Show more" button from the OpenTextSummary:
https://github.com/formbricks/formbricks/pull/2160
Unfortunately, this button is quite important to get a quick overview of the latest comments. It would therefore be super cool if it could be reintroduced.

### Steps to Reproduce

1. Open a survey with more than 10 open text comments
2. Try to read the 11th comment

### Expected behavior

You can see all responses (or the next e.g. 10) when you click on the "Show more" button.

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- v1.6.1
```

**Comment by mattinannt** [comment]
@gupta-piyush19 Do you see a good option that we can solve this without messing with the whole server-side summary concept?

**Comment by gupta-piyush19** [comment]
Hey @jonas-hoebenreich , Thanks for pointing out this bug 😊
I anticipated this bug since the limit of openText answers is only 10, and to solve this, I have two ideas to work on:
1. We can increase the limit to 50 and give a "show more" button after every 10 answers to unroll up to 50 answers.
2. We can add a new service to query the database based on the questionId and current filters to fetch the next 10 answers until the very last answer, but in this approach, we would need to merge this data into the summary data, which is a bit tricky to handle due to the complex nature of the summary page.
What do you think is the approach that suits your use case?
I am happy to discuss this.

cc: @mattinannt

**Comment by jonas-hoebenreich** [comment]
So these are my thoughts on the two variants:
1. This doesn't really solve the problem, but rather shifts it. Since the survey summary is the only place in the UI where you can get a good overview of all answers to a question, I think it shouldn’t be limited to just 50 answers.
2. I get that this approach is a bit more complicated. Maybe it's a bit simpler when you implement it like this:
a. user clicks "show more" button
b. API returns all responses to that question
c. in frontend, remove existing table and show new table with first 20 answers from API call
d. add a new "show more" button at the end of the table that unrolls the next chunk of answers

**Comment by mattinannt** [comment]
@jonas-hoebenreich The issue is with step 2.b since our data model doesn't really allow to give us the option yet to efficiently query for responses to a single question. But it's also likely that we might change the data model in the future to allow this and other queries. But it's not a feature we can provide in the near feature.

The quick fix with increasing the limit of responses a user can see in the summary would be the only solution we can offer now until we revamp the data model.

We also see the summary view more like a view where you can see the aggregated responses. For viewing single responses you should use the responses page and set up filters if you would e.g. only see responses where a certain question is answered. We also already prepared the ticket for a new more powerful responses view where you can see more information at a glance with a customizable data table and will start development soon.

**Comment by jonas-hoebenreich** [comment]
Ok, thanks for the explanation, sound good 👍
