### ISSUE TITLE
[FEATURE] Autoclose of surveys

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#2360]
### Is your feature request related to a problem? Please describe.

I propose revisiting the current default setting of automatically closing new in-app surveys after reaching 50 responses. The toggle, often tucked away in a collapsed accordion, risks being overlooked. From your Formbricks Cloud standpoint, this default setting might also not align with your business interests.

### Describe the solution you'd like

I suggest making the auto-close feature opt-in by default, rather than opt-out. This means that the auto-close function would be disabled by default, allowing users to manually set their desired response threshold if they wish to limit the number of responses. 
I can open a PR for this if you want.

**Comment by jobenjada** [comment]
makes sense :) we initially set it because we had some users with surveys with 1000s of responses and they could've got a statistically relevant insight much earlier. They "wasted" the willingness of many of their users responding to a survey which wouldn't yield any additional insight.

but it's probably better to keep it default off as this would be expected and then make these kind of suggestions in a notification once a survey reached a certain number of responses. So feel free to open a PR for it - appreciate it :)

**Comment by jonas-hoebenreich** [comment]
Thank you very much for taking care of this already 💪
