### ISSUE TITLE
[FEATURE] Copy surveys between products

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#2630]
### Is your feature request related to a problem? Please describe.

forms are stuck in a product

### Describe the solution you'd like

move between products or
build export and import of surveys

### Additional context

This issue was requested by Formbricks users multiple times, e.g.
```
Message: I'd like to move a form from a product to another
```

**Comment by mattinannt** [comment]
To avoid conflicts with the existing responses I would slightly change the functionality from "move" to "copy" and extend the existing "Copy to dev" functionality.

Instead we will rename it to `Copy...` and let it open a modal where the user can configure where the survey should be copied to:

<img width="201" alt="Screenshot 2024-05-15 at 16 49 40" src="https://github.com/formbricks/formbricks/assets/675065/d67f53d4-cc01-455c-a68a-e22fbfe838d2">

![copy-survey](https://github.com/formbricks/formbricks/assets/675065/e6257183-f0c2-48c9-b346-2c52be577129)

Please use react-hook-form to solve this form and rewrite the existing "copy to dev" functionality to be more versatile and be able to copy this over to an environment of the users choice.

**Comment by Kiran-Alex** [comment]
Hey @mattinannt @jobenjada, could you please review my PR #2666 ? I would like to work on this issue once that PR is closed. Thank you!

**Comment by git-init-priyanshu** [comment]
Hello maintainers, sorry to bother you, I know this issue cannot be assigned to me because I don't have enough points at this moment but can you please assign this issue to me? I have successfully coded it locally and it is working great. 
[Screencast from 30-05-24 08:00:15 PM IST.webm](https://github.com/formbricks/formbricks/assets/110045644/4f484cf2-66b6-4451-9e55-c0d2093ffa04)
Of course, I completely understand if assigning it to me is not feasible now and I respect your decision. Thank you for considering my request.

**Comment by parthgupta118** [comment]
Hey @jobenjada @mattinannt!
If this is a higher priority issue,
Could you guys please take a look at this issue and finalise who the ticket should be assigned to?

Thank you! 🙏

**Comment by smritidoneria** [comment]
Kindly review the pr 2832

**Comment by smritidoneria** [comment]
@mattinannt  kindly review the pr #2832
