### ISSUE TITLE
[FEATURE] Pop-up builder

### ISSUE THREAD

**Issue by saenzramiro** [formbricks/formbricks#2793]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Have the ability to display pop-ups with texts, buttons, fields, images, etc. to show information to the user, like promotions, hints/tips, a welcome message, etc. The idea is similar to [GetSiteControl](https://getsitecontrol.com), [Popupsmart](https://popupsmart.com), [plum](https://plumpopup.com/) and many others.

### Additional context

I think that is not a hard feature to implement because the user segmentation that you have (metadata and segments), the actions and all the logic you already implemented for surveys can fit perfectly to pop-ups.
There are some open source no-code builders (like https://github.com/NiazMorshed2007/popwola) that can be implemented and improved to add it to Formbricks.

**Comment by mattinannt** [comment]
@saenzramiro Thanks for creating an issue :-) 

Formbricks aims to be an experience management solution tailored to help companies measure and evaluate the feedback and insights they get from their customers.
We need to evaluate if diving deeper into the use case of presenting information to the user without getting insights from them is a good product decision, as adding more features also adds complexity and makes the product harder to use overall.

I will keep the topic open so that other users can comment with their use cases for pop-ups and we can see how we can support this with Formbricks 😊.

**Comment by mattinannt** [comment]
We discussed this feature suggestion again within the team and decided not to put it on the roadmap as it's not the main use case for Formbricks, which is focused on surveys in the experience management space with analysis of that data.
