### ISSUE TITLE
[BUG] [Summary] Clicking 'load more' on an 'Other' field applies a filter

### ISSUE THREAD

**Issue by ag-gaphp** [formbricks/formbricks#3141]
### Issue Summary

When viewing the Summary screen for a survey that has an 'Other' field in multipleChoice questions, there is a 'load more' button that appears if there is a long list of user inputs.

If you click this button, a view filter is applied to the whole summary list.

### Steps to Reproduce

1. Create survey with at least 1 multipleChoice type question
2. Add an 'Other' field to the multipleChoice question
3. Submit responses, being sure to put in several different unique inputs for 'Other' (5-10 submissions)
4. View the survey's summary and scroll to the multipleChoice question
- _Observe_: A list of 'Other' user inputs is present, with a 'load more' button
![image](https://github.com/user-attachments/assets/dd9ae97a-dd3b-4ce9-9371-b54687b16e3a)
5. Click 'load more'
- _Observe_: There is a notification banner that indicates a filter has been applied
![image](https://github.com/user-attachments/assets/5bedb3d9-4ddc-4d6c-8066-fb8519b3a8c7)

### Expected behavior

No filter is applied

### Other information

One of our surveys has a lot of questions with this 'Other' field. Most of the time I want to keep the full summary, but only view all the 'Other' inputs, then keep scrolling through the rest of the data.

With the way it functions now, I have to:
1. Scroll to the question
2. Click load more to see all the inputs
3. Scroll back to the top of the page to clear the filter
4. Scroll back down to the next question and start over

**NOTE**: This only occurs on miltupleChoice type questions. openText type questions with a 'load more' button simply expand the list without applying a filter.

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: NixOS
- Formbricks: 2.5.1
- Official Docker Image
```

**Comment by neehhaa06** [comment]
Hello @ag-gaphp :)

fix: #3141

The problem occurs when clicking the 'load more' button for 'Other' fields in multiple-choice questions, as it inadvertently applies a filter to the entire summary view. This unintended filtering requires users to manually clear the filter to view all responses, disrupting their workflow. The solution is to modify the functionality so that 'load more' simply expands the list of 'Other' inputs without altering the summary view, ensuring a consistent and smooth user experience.
