### ISSUE TITLE
[🕹️] Build NPS Calculator

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3190]
### What side quest or challenge are you solving?

To attract visitors to our landing page, we aim provide a simple NPS calculator as a free tool on [formbricks.com](http://formbricks.com/).

Here is an example: https://www.surveymonkey.com/mp/nps-calculator/

### Points

750

### Description

Link to the application form will be added on October 1st  🚀

### [Apply here](https://app.formbricks.com/s/cm1nxig3k0001lsou303bih6h)

**Comment by syedbarimanjan** [comment]
@jobenjada I tried to apply to this issue but the problem is that on the second step it is asking 

`Which article do you want to write?`

I dont understand do i have to write an article on this? 

I have created a calculator for [maybe](https://maybe.co/) which is also an opensource project [here](https://github.com/maybe-finance/marketing/pull/58) is the pr for it. I love maths and am confident that i can build this if you give me a chance.

**Comment by jobenjada** [comment]
@syedbarimanjan you're right, the form was wrong. You're already working on the docs PR so pls ship that first :)

The issue is still up for grabs!

**Comment by syedbarimanjan** [comment]
> @syedbarimanjan you're right, the form was wrong. You're already working on the docs PR so pls ship that first :)
> 
> The issue is still up for grabs!

Hi i want to work on this one first i have removed my assignment from the docs issue.

**Comment by jobenjada** [comment]
@syedbarimanjan pls ping me on Discord and I'll get you access to the formbricks LP repo :)

**Comment by adityadeshlahre** [comment]
Hey @syedbarimanjan can you confirm that you are working on this issue? {open draft PR}
If not would like to pickup this one :slightly_smiling_face: 
Thank You

**Comment by jobenjada** [comment]
havent heared from him - up for grabs :)
