### ISSUE TITLE
[🕹️] Article: How to run an in-app survey in your React Native App

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#3196]
### What side quest or challenge are you solving?

Article name: How to run an in-app survey in your React Native App

### Points

1500

### This gives A LOT of points because writing a high quality technical article with good instructions, screenshots, etc. can take a full day or more 🤓

Here is the [Formbricks Writing Guide](https://formbricks.notion.site/FormTribe-Content-Writing-Guide-f6464ee837364785afdc6c88ef8bfd51?pvs=74)

### Provide proof that you've completed the task

I'll share a link to apply **with your previous work** for this task.

**Comment by KartikDevarde2601** [comment]
Hi @jobenjada, I have experience with Expo and React Native CLI. Could you please assign  this task to me.

**Comment by KartikDevarde2601** [comment]
I noticed that **react-native-web-view** does not automatically install when we install the package because it is listed under peerDependencies. We could consider moving it to devDependencies to streamline the installation process for developers, reducing the number of steps required during setup. This change could enhance the developer  experience.

**Comment by jobenjada** [comment]
@KartikDevarde2601 thanks for your interest! :) Do you have experience writing technical articles?

Here are the requirements: https://formbricks.notion.site/Formbricks-Content-Writing-Guide-f6464ee837364785afdc6c88ef8bfd51?pvs=4

**Comment by jobenjada** [comment]
the issue is yours, there's always a first time and open source is great to learn a new skill 🤓

**Comment by jobenjada** [comment]
up for grabs again :)

**Comment by RajuGangitla** [comment]
@jobenjada can i take this one

**Comment by RajuGangitla** [comment]
@jobenjada can you check this article and give feedback 
https://dev.to/raju_gangitla_91920e1427f/in-app-surveys-made-simple-with-formbricks-in-react-native-a-complete-guide-o9e

**Comment by Jatin2345-png** [comment]
I have created and merged the pull request that addresses this issue. The changes are now in the main branch.

@jobenjada , please review the updates:

- [Pull Request #1](https://github.com/Jatin2345-png/formbricks/pull/1)
- [Commit #bc4935f](https://github.com/Jatin2345-png/formbricks/commit/bc4935fff695f9bc5e74195cbdadb44bbe4d8941)

The issue is now closed. Let me know if there are any further actions required.

**Comment by Jatin2345-png** [comment]
> @Jatin2345-png, please open a draft PR linking this issue within 12 hours. If we can't detect a PR in 12 hours, you will be unassigned automatically.

https://github.com/formbricks/formbricks/issues/3196#issuecomment-2437356813

**Comment by Khaan25** [comment]
@jobenjada, Can I work on this?
