### ISSUE TITLE
[BUG] Internal Server Errors still shows success toast

### ISSUE THREAD

**Issue by jonas-hoebenreich** [formbricks/formbricks#3302]
### Issue Summary

Sometimes internal server errors occur and the next server will respond with a `serverError: "Something went wrong while executing the operation."` (but still status code 200). Because of status 200 the frontend will not recognize it as an error and will still show a success toast (although something went wrong).
Formbricks should check the responses for a serverError when accessing backend functions:

```
if (result?.serverError) {
    throw new Error("Something went wrong");
}
```

### Steps to Reproduce

1. Use eg #3301 to trigger an unsuccessful server only action
2. success toast will pop up although the operation actually failed

This happens in many places where the toast will pop up when there is no error during a server side action.

### Expected behavior

An error toast indicating the issue pops up (instead of falsely suggesting a successful operation)

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- all Browsers
```

**Comment by jonas-hoebenreich** [comment]
I can work on this if you want :)
/assign

**Comment by jobenjada** [comment]
sure, sounds good :)

**Comment by BadriVishalPadhy** [comment]
if [jonas-hoebenreich] isnt able pls assign this issue to me

**Comment by BadriVishalPadhy** [comment]
hey @jobenjada  can u assign this issue to me

**Comment by BadriVishalPadhy** [comment]
@jonas-hoebenreich can u let me do this?

**Comment by Git-Suraj-hub** [comment]
award 100

**Comment by RubenRuCh** [comment]
I created a [small bounty](https://app.opire.dev/issues/01JARC75G44M6EQCJCR1DTBHD6) for this

**Comment by rithikchalla** [comment]
Is the issue closed or open to work?

**Comment by mattinannt** [comment]
Closing for now as we have implemented this in several places. If the issue persist on a specific page, please open a new issue for this :-)

**Comment by sungdark** [comment]
我来认领！

收款地址：eB51DWp1uECrLZRLsE2cnyZUzfRWvzUzaJzkatTpQV9

已提交 PR: https://github.com/formbricks/formbricks/pull/7616

**Comment by sidneisilvadev** [comment]
/try

---
**Carteira para pagamento (Polygon):** `0xbB496fc12949388326267FC111dca46F1226062d`

**Comment by Ltbltbltbltb** [comment]
## Root Cause Analysis

The issue stems from Next.js server actions returning `{ data: ..., serverError: "..." }` with HTTP 200 when an internal error occurs. The frontend only checks for the presence of `data` to determine success, missing the `serverError` field entirely.

The fix suggested in the issue (`if (result?.serverError) { throw new Error(...) }`) has been applied in several places, but **two locations still show the original pattern**:

### 1. `apps/web/modules/survey/list/components/survey-dropdown-menu.tsx` (line ~108)

```tsx
// Current (buggy) — serverError not checked
if (duplicatedSurveyResponse?.data) {
  // ...
  toast.success(t("environments.surveys.survey_duplicated_successfully"));
} else {
  const errorMessage = getFormattedErrorMessage(duplicatedSurveyResponse);
  toast.error(errorMessage);
}
```

```tsx
// Fix
if (duplicatedSurveyResponse?.data && !duplicatedSurveyResponse?.serverError) {
  // ...
  toast.success(t("environments.surveys.survey_duplicated_successfully"));
} else {
  const errorMessage = getFormattedErrorMessage(duplicatedSurveyResponse);
  toast.error(errorMessage);
}
```

### 2. `apps/web/modules/survey/multi-language-surveys/components/edit-language.tsx` (line ~116)

```tsx
// Current (buggy)
if (surveysUsingLanguageResponse?.data) {
  // shows modal or proceeds
} else {
  const errorMessage = getFormattedErrorMessage(surveysUsingLanguageResponse);
  toast.error(errorMessage);
}
```

```tsx
// Fix
if (surveysUsingLanguageResponse?.data && !surveysUsingLanguageResponse?.serverError) {
  // shows modal or proceeds
} else {
  const errorMessage = getFormattedErrorMessage(surveysUsingLanguageResponse);
  toast.error(errorMessage);
}
```

These can be triggered by the same mechanism described in #3301 — when the server action throws internally and next-safe-action wraps it as `{ data: undefined, serverError: "Something went wrong..." }` while still returning 200.

I'll open a PR with these two targeted fixes.

/try

**Comment by fansifei** [comment]
C:/Program Files/Git/try

**Comment by jhxhu02** [comment]
Hi! I have successfully resolved this issue in two additional files where the `serverError` was not checked before showing success toasts:
1. `apps/web/modules/survey/list/components/survey-dropdown-menu.tsx` (survey duplication toast)
2. `apps/web/modules/ui/components/data-table/components/selected-row-settings.tsx` (refined the bulk delete using `Promise.allSettled` to robustly update UI only for successfully deleted rows even on partial server action failure).

Since PR creation is restricted to collaborators to prevent AI spam, I have pushed the complete, tested fix to my fork here:
https://github.com/jhxhu02/formbricks/tree/fix-server-action-toasts

And here is the direct diff of the changes:
https://github.com/formbricks/formbricks/compare/main...jhxhu02:formbricks:fix-server-action-toasts

Maintainers can easily merge this branch. I would highly appreciate it if the bounty on Opire could be awarded to this solution! (Also, due to regional Stripe Connect KYC limits, I would appreciate a manual crypto/Bybit card payout if possible). Thank you!

**Comment by raphaelodiweaugustine-jpg** [comment]
Hi team, I have completed the fix for this issue (Internal Server Error handling during CSV upload). I have verified the fix in my fork and have signed the CLA.

You can review my work and merge it here: [Paste your PR Link: [https://github.com/raphaelodiweaugustine-jpg/formbricks/pull/1](https://www.google.com/search?q=https://github.com/raphaelodiweaugustine-jpg/formbricks/pull/1)]

Please let me know if you need me to do anything else to get this contribution into the main repository!

**Comment by qikezhang** [comment]
Hi there! I have successfully identified and fixed this issue by adding robust try-catch error handling and descriptive toast alerts in `data-table-toolbar.tsx` to prevent silent 500 server-side failures (with clean and standard English comments).

I would love to submit a Pull Request for this! Here is the clean and fully verified branch on my public fork:
https://github.com/qikezhang/formbricks/tree/feat/fix-server-error-toast-3302

Could you please assign this to me, or add me as a collaborator so I can open the Pull Request directly? Thank you so much!

/claim

**Comment by qikezhang** [comment]
Hi there! I have just updated my fork branch (`feat/fix-server-error-toast-3302`) to include a critical second fix in `survey-dropdown-menu.tsx` (the survey duplicate action toast was also missing the `serverError` check and could trigger false success toasts on 500 server-side error). My branch is now the most comprehensive, robust fix addressing all residual occurrences of this issue. Looking forward to your review and merge! Link: https://github.com/qikezhang/formbricks/tree/feat/fix-server-error-toast-3302

**Comment by arjunannamalai** [comment]
Hi Formbricks Maintainers! 

I have successfully resolved this issue and created a fully tested fix on my fork: 
 [arjunannamalai/formbricks@fix-toast-notification-bug](https://github.com/arjunannamalai/formbricks/tree/fix-toast-notification-bug)

### Root Cause
The bug occurs in the client-side handlers inside `targeting-card.tsx`. When Next.js server actions (like `createSegmentAction`, `updateSegmentAction`, `loadNewSegmentAction`) fail, they return a status code 200 with `{ serverError: "..." }`. 
Because no exception was thrown, the calling modal `try...catch` blocks completed successfully (treating the returned `undefined` data as valid), which mistakenly triggered green success toasts (`toast.success`) instead of error alerts.

### Proposed Fix
We updated the action wrappers in `targeting-card.tsx` to check for `serverError` and throw a formatted error using `getFormattedErrorMessage(result)`. This forces the calling modals to successfully catch the error and display a red `toast.error(err.message)`.

Here is the exact diff:
```diff
diff --git a/apps/web/modules/ee/contacts/segments/components/targeting-card.tsx b/apps/web/modules/ee/contacts/segments/components/targeting-card.tsx
index a24ac6b00..fcf24bbc3 100644
--- a/apps/web/modules/ee/contacts/segments/components/targeting-card.tsx
+++ b/apps/web/modules/ee/contacts/segments/components/targeting-card.tsx
@@ -123,16 +123,25 @@ export function TargetingCard({
 
   const handleLoadNewSegment = async (surveyId: string, segmentId: string) => {
     const updatedSurvey = await loadNewSegmentAction({ surveyId: surveyId, segmentId });
+    if (updatedSurvey?.serverError) {
+      throw new Error(getFormattedErrorMessage(updatedSurvey));
+    }
     return updatedSurvey?.data as TSurvey;
   };
 
   const handleSaveAsNewSegmentUpdate = async (segmentId: string, data: TSegmentUpdateInput) => {
     const updatedSegment = await updateSegmentAction({ segmentId, data });
+    if (updatedSegment?.serverError) {
+      throw new Error(getFormattedErrorMessage(updatedSegment));
+    }
     return updatedSegment?.data as TSegment;
   };
 
   const handleSaveAsNewSegmentCreate = async (data: TSegmentCreateInput) => {
     const createdSegment = await createSegmentAction(data);
+    if (createdSegment?.serverError) {
+      throw new Error(getFormattedErrorMessage(createdSegment));
+    }
     return createdSegment?.data as TSegment;
   };

**Comment by buxiangcifan123** [comment]
Hi @Dhruwang and Formbricks team,

I have prepared a fix for this issue but found that the repository restricts pull requests to collaborators only.

**My fix:** Added an `isActionSuccessful()` type guard in `lib/utils/helper.ts` and applied to 4 core survey operation files.

**Diff:** https://github.com/formbricks/formbricks/compare/main...buxiangcifan123:fix/servererror-toast-guard

Could you either grant me temporary collaborator access to submit the PR, or review the changes directly from my branch? Happy to adjust anything.

Thanks!

**Comment by erikthegooner** [comment]
I have a fix ready for this — PR incoming.
