### ISSUE TITLE
[FEATURE] Edit and Resolve Notes

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#390]
**Is your feature request related to a problem? Please describe.**
As a user I cannot edit or resolve notes.

**Describe the solution you'd like**
Allow to edit and completely hide notes

**Tasks**

1. Make notes editable. On hover next to the actual note (in this case the text “That’s a note”) display a small pen icon. On click, the note is loaded back into the textarea for the user to update it. The Button text change to “Save” and once saved, a little “ (edited) “ appears next to the note text in the same format like the date.

![grafik](https://github.com/formbricks/formbricks/assets/72809645/cb8a7285-c05d-4bc1-abd9-d0a34b2617b4)

1. Make notes resolveable. Next to the Minimize icon, add a checkmark icon. The icon will hide the note completely so that no notes indiciator is shown anymore. This is the notes indicator which should be hidden after resolve:

![grafik](https://github.com/formbricks/formbricks/assets/72809645/3ea26ad2-291a-470b-9392-4e45e963f3c9)

The easiest way would be to delete the note but we might want to allow people to reopen them down the line.

## How to code for Formbricks
1. Make sure everything is type-safe
2. If you run `pnpm dev` you'll find a demo app to test in-app surveys at `localhost:3002`
3. When your code is done and working, paste it to chatGPT and ask for refactoring ideas. Apply what makes sense to you (GPT-4 is a lot better). Try out our new [Formbricks-Prompt](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) ✨

**Comment by pandeymangg** [comment]
@jobenjada Could you please assign this issue to me

**Comment by gl0git** [comment]
I'd like to work on this issue

**Comment by jobenjada** [comment]
you got it :)

**Comment by gitstart-formbricks** [comment]
@jobenjada Is this ready to be worked on?

**Comment by kuluruvineeth** [comment]
@jobenjada, could we please discuss on these two points for more clarifications for the above PR to be complete, so that i can go ahead and implement them too : 
 - [ ] once saved, little “ (edited) “ appears next to the note text in the same format like the date. Could i go ahead and make change for this too by adding additional column in responseNote model like isEdited: boolean and then make necessary changes.
- [ ] Need Clarification : Make notes resolveable. Next to the Minimize icon, add a checkmark icon. The icon will hide the note completely so that no notes indiciator is shown anymore. This is the notes indicator which should be hidden after resolve. On clicking on checkmark icon we will hide the note completely, but to reopen it where should we handle it i mean should we place icon next to delete icon or you have something in mind, Please lets discuss on this.
