### ISSUE TITLE
[FEATURE] As a user I want to embed the link survey via iframe

### ISSUE THREAD

**Issue by jobenjada** [formbricks/formbricks#402]
**Is your feature request related to a problem? Please describe.**
![grafik](https://github.com/formbricks/formbricks/assets/72809645/73cf5edd-ca1c-4940-aca6-b08bfc004b85)

**Describe the solution you'd like**
While the survey is already iframable, it could be made easier for our users.

**Tasks**
1. Add a button "Embed" with a CodeBrackets icon next to Preview:
![grafik](https://github.com/formbricks/formbricks/assets/72809645/48e7c48b-4d3b-4aa0-99a9-aad3ae0ed7a7)

2. On click, switch the URL out with a CodeBlock (see formbricks/ui) which contains the needed code to embed the form with an iframe. **Make sure its responsive.**

**Comment by Ankur-Datta-4** [comment]
@jobenjada I'd like to work on this

**Comment by jobenjada** [comment]
cheers, thanks Ankur! :)

**Comment by Ankur-Datta-4** [comment]
Just a clarification needed @jobenjada 

Should the resulting UI look like this:

![WhatsApp Image 2023-06-18 at 21 00 03](https://github.com/formbricks/formbricks/assets/75306530/4f9811ea-cfeb-4e1d-a11c-81397eb69662)

Onclick-embed:
![WhatsApp Image 2023-06-18 at 21 00 28](https://github.com/formbricks/formbricks/assets/75306530/27d03d39-7367-4835-8f83-69821444db99)

Since, there's a scrollbar for the embed code, responsiveness is guaranteed.

Just clarify if this was the required feature. 

Further:
- I noticed that once the user would click on embed, there's no toggle to go back to the link, so lmk how to tackle this, if required

**Comment by jobenjada** [comment]
hey mate!

1. Please grow the CodeBlock window to three or four lines (height) and and match the styling of the URL window (border, border-radius).
2. Please make "Preview" the main CTA (move it to the right end, change the variant to "darkCTA")
3. On "Copy URL" display the input with the URL and copy it to the clipboard, display a success toast "URL copied to clipboard."
4. On "Embed" display the CodeBlock, copy the code ti clipbpoard and display a success toast "iframe code copied to clipboard."

This should solve it :)

Thanks for following up! 🙏

**Comment by Ankur-Datta-4** [comment]
Out of the 4 requirements 2,3,4 was fulfilled.
Codeblock doesn't have properties of border-radius. But, I have expanded to increase height
Check it out:

https://github.com/formbricks/formbricks/assets/75306530/98e5c176-888f-4d00-b415-33ef40569ef5

**Comment by Ankur-Datta-4** [comment]
But this would mean that I can't use CodeBlock component. 
Also found that CodeBlock component is internally built using the code you gave, so its a given that it'd work.
