### ISSUE TITLE
[🕹️] sidequest Billboard Ad

### ISSUE THREAD

**Issue by AshishViradiya153** [formbricks/formbricks#4089]
### What side quest or challenge are you solving?

total: 450

point: 150
GIf: https://x.com/Ashish129570796/status/1850435194894897553
giphy: https://media.giphy.com/media/WXzhvJjhctqHStDMTK/giphy.gif
<img width="558" alt="Screenshot 2024-10-29 at 12 30 04 AM" src="https://github.com/user-attachments/assets/4e8ed600-dd45-4b8b-bbf9-7ef8c8d56329">

Billboard Ad (300 Points):

![banner](https://github.com/user-attachments/assets/7230b10d-db5a-4411-8b74-6442d7aed59d)

### Points

300

### Provide proof that you've completed the task

image

**Comment by jobenjada** [comment]
you already got points for making a meme mate, we have a 0 tolerance policy for cheaters.......

**Comment by AshishViradiya153** [comment]
@jobenjada, you're thinking wrong! It's not a meme; it's a GIF. I never submitted a GIF.!!

**Comment by AshishViradiya153** [comment]
i just porsted on X GIF!!

**Comment by AshishViradiya153** [comment]
@jobenjada, could we please clarify this?

**Comment by jobenjada** [comment]
here you claimed 300 points (150 for meme and 150 for GIF) and in this one you claim another 150 for the GIF: https://github.com/formbricks/formbricks/issues/4053

Also in this one you claim 100 points for following Formbricks which wasn't a quest:
https://github.com/formbricks/formbricks/issues/3969

im sorry that your efforts are in vain but we have a 0 tolerance for cheating because we cant possibly control everything with thousands of people participating.

your actions show that you did not have the intentions to play fairly and we cant allow that to happen - its unfair to all the other players.

sorry, but you're disqualified :(

**Comment by jobenjada** [comment]
// marc @ Papermark vouched for you due to your extensive code contributions, so you're qualfied again. Doesnt make sense to spend days writing code and then cheat for 250 points. 

ill remove the duplicate points - good luck at the raffle!
