### ISSUE TITLE
Scheduled surveys not running on date

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#4243]
### Issue Summary

<img width="829" alt="Screenshot 2024-11-05 at 13 12 25" src="https://github.com/user-attachments/assets/b8495888-5ca4-4a45-a451-55a023d88ace">

### Other information (incl. screenshots, Formbricks version, steps to reproduce,...)

Discord Message: https://discord.com/channels/979077669410979880/1303315491170811934/1303315491170811934

### Your Environment

Formbricks Cloud (app.formbricks.com)

**Comment by dhruv1707** [comment]
Hey @mattinannt,
I dug deep into the code and it seems like the issue is - the runOnDate has been set to UTC (12:00 am) which may be different for each user depending on their time zones.
Here's a screenshot of the original code to show it you:
<img width="526" alt="Screenshot 2024-11-10 at 8 01 03 PM" src="https://github.com/user-attachments/assets/4fd31ab3-088a-45fd-a6b8-ced2160f9a54">

However, I have fixed this issue now to take into account the user's local time zone and set the runOnDate to the beginning of day (the local time zone) equivalent to UTC for consistency with their time zones. Here's the changes (of course I will make this code even cleaner ;)):

<img width="598" alt="Screenshot 2024-11-10 at 8 24 57 PM" src="https://github.com/user-attachments/assets/a31ac549-8845-4e94-ae26-3081b34cf8c8">

But before proceeding to creating a pull request I wanted to confirm if this is what is even intended for the functionality since the response options card clearly mentions: "Automatically release the survey at the beginning of the day (UTC)." which will have to be changed on the UI side?

Let me know what you think and I can proceed accordingly! :)

Thanks,
Dhruv

**Comment by mattinannt** [comment]
We found the issue. It was a misconfiguration of cron jobs on Formbricks Cloud.
