### ISSUE TITLE
[FOR-809] [FEATURE] Option to SurveyTrigger condition between "and" and "or"

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#425]
**Is your feature request related to a problem? Please describe.**
With more pages and actions a user might want to setup more complex triggers for surveys. e.g. only trigger this survey only on the homepage and only when the user scrolls down 50% (currently under development as a PR).
But currently a user can only setup `or` conditions between triggers, meaning "when on homepage or scrolled (on any page) down 50%"

![](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/2342a6f7-9336-437c-ac88-708f6e0a2e0e/f1e79dcb-f8e6-4f65-bfe6-4072e049fa85)

**Describe the solution you'd like**
Add the option to change the `or` condition to an `and` condition with a dropdown in the Survey Trigger options while creating or updating a survey. Also change the event logic in formbricks-js to reflect these changes.

![](https://uploads.linear.app/3fe97322-d3ec-4707-9405-83aa0b6c061d/295aea49-faf5-4956-bda5-2eb138978df9/c3f49b6a-478b-48b0-8410-f788de248bee)

<sub>From [SyncLinear.com](https://synclinear.com) | [FOR-809](https://linear.app/formbricks/issue/FOR-809/[feature]-option-to-surveytrigger-condition-between-and-and-or)</sub>

**Comment by Ankur-Datta-4** [comment]
Just some clarification required @mattinannt :
Does the issue want us to do just 1 level of condition across 2 items like (A or B) , (A and B)
or 
Are we gonna have a recursive-tree of conditions like:
![image](https://github.com/formbricks/formbricks/assets/75306530/e3b8685b-e95b-41e8-a51b-23772563d2ee)

Cos then:
- We'll have to serialize triggers and store it in a format like that.
- Have a recursive evaluation condition instead of simple iteration-return: https://github.com/formbricks/formbricks/blob/a1bbe5c5fb178a01896450ceafc437805d18f77c/packages/js/src/lib/event.ts#L55
- So complexity of this would 🚀

**Comment by mattinannt** [comment]
@Ankur-Datta-4 , thanks for putting so much thought into this 😊. We are currently having similar discussions when it comes to response filtering and audience filtering.

I realized that there is a basic flow in my idea of this functionality as it doesn't really make sense to have an 'AND' connection between events since events can't happen at the same time.
What I need is more of a filter on the surveys to only qualify a survey when a specific event has already happened and then the survey is shown on the trigger.
I will think about this and come up with an approach next week 😊

**Comment by Ankur-Datta-4** [comment]
Sure sure, works!

**Comment by Ankur-Datta-4** [comment]
@mattinannt Any updates about the approach?

**Comment by mattinannt** [comment]
Because of the problems we ran into in this issue, we rethought the approach and came up with an `Advanced User Targeting` Feature that solves this issue and also other issues we had in one well thought out feature: https://github.com/formbricks/formbricks/issues/612
