### ISSUE TITLE
Date-picker

### ISSUE THREAD

**Issue by mattinannt** [formbricks/formbricks#51]
### Add Date-picker

As a user I want to allow respondents to pick a date in a calendar.

This feature needs to be added to the snoopforms-react library as well. Here also things like package-size & customisability needs to be considered.

**Comment by b4s36t4** [comment]
@matthiasnannt Can I work on this part?!

**Comment by matthiasnannt** [comment]
@b4s36t4 Sure :-) The only thing you need to consider is that this affects not only the snoopforms platform but also the snoopforms react library, because there you need the date-picker as well. If you need any help with that we can also have a quick call. You can schedule a call with me via: https://cal.com/matti-nannt/onboarding

**Comment by b4s36t4** [comment]
<img width="634" alt="Screenshot 2022-08-18 at 12 15 25 AM" src="https://user-images.githubusercontent.com/59088937/185218507-9727f886-a85b-4c2e-9d98-b8aec223759e.png">
@matthiasnannt How does this look? For more info, I scheduled a meet for tomorrow (18th Aug) between us. Please let me know how's this looking

**Comment by mattinannt** [comment]
A lot changed in the snoopForms / Formbricks journey and a lot of thanks for your contributions even though it never went into production 🙏. I am now closing this issue due to the ongoing migration to Formbricks with a completely new code base.
