### ISSUE TITLE
[FEATURE][FormTribe 🔥][150 Points] Prohibit two identical product names

### ISSUE THREAD

**Issue by adityadeshlahre** [formbricks/formbricks#994]
### Issue Summary

Multiple Product and Team can be added with same name!
This issue can lead to confusion to user working with several teams on different products !
And it get disappear after few minutes .

### Steps to Reproduce

Click on the profile Avatar :

**For Product**
1.click on [My Product] product button .
2.At drop down click on [+ Add Product] button
3.Fill name[newproduct] in Name (fill up)

Follow step 1 <to> 3 few times !

**For team**
Currently its not showing up the newly created team but u can see it few minutes after creating multiple team with same name

1.click on [<user> team] Team button .
2.At drop down click on [+ create team] button
3.Fill name[newTEAM] in Name (fill up)

Follow step 1 <to> 3 few times !

after doing this you will see multiple Product/Team with same name in the dropdown menu !

Again logout & login or after few minutes it will get disappeared ! ( don't know the exact timing )
**Note : after logout & login multiple entries of products get disappear but team name still there !**  

### Expected behavior

Since it get disappeared ! ( logout and login )
it should check list of previously added [product/team names] and throw errors team already exist !

or 

different solutions can be implemented ! 

### Screenshots

Product : 
https://www.loom.com/share/1bc4c0b6bb9b4136bc8c407bbabd51d4?sid=ce312efe-c3c6-40c9-a596-ff94ecd3c807

Team Name ;
https://www.loom.com/share/0dbbaa2d700c45c88add80b844f0c9f9?sid=09de555a-d897-4b53-a709-8729a87bb485

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by adityadeshlahre** [comment]
@jobenjada please confirm this once from your sides though it is valid or not !

Thank You :smile:

**Comment by anjy7** [comment]
Does this issue still persists after removing that unstable cache function? @adityadeshlahre

**Comment by adityadeshlahre** [comment]
yeah @anjy7 it is still there even after removing unstable_cache function !

**Comment by anjy7** [comment]
Okay I'll look into this @adityadeshlahre

**Comment by mattinannt** [comment]
@anjy7 @adityadeshlahre Technically we don't need the team or product name to be unique.
Multiple products with the same name in a team can be confusing and we shouldn't allow this.
But I'm not sure with team names in general, as normally it doesn't lead to problems easily because most likely a user is not of both teams. I will discuss this with the team :-)

**Comment by jobenjada** [comment]
We have decided to not allow identical product names within a team but allow several teams with the same name. 

Will transform this into a Feature request 👍

**Comment by jobenjada** [comment]
@adityadeshlahre I have assigned you to this issue because you flagged it :) Please let me know if your up for to fix it and if not unassign yourself pls.

From a UX point of view, you can simply validate in the Create Product modal:

<img width="611" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/3215824d-781e-4cf9-9e95-be2445ff61b9">

Like so + disable button (sorry for quick and dirty mock up :D )

<img width="884" alt="image" src="https://github.com/formbricks/formbricks/assets/72809645/081a813d-5476-436a-9ac0-8ad6e857a95b">

### Thanks!

**Comment by adityadeshlahre** [comment]
since there is already a PR of @anjy7 is created u can assign him and he can proceed with fix !
thanks you :smile:

**Comment by jobenjada** [comment]
Yeah just saw it! https://github.com/formbricks/formbricks/pull/996

@anjy7 your solution with the toast also works :) 🙏
